const phone = [
  {
    id: 1,
    image: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s8-.jpg",
    name: "samsung galaxy s8",
    launch: "2017, march 29",
    body: "148.9x68.1 mm",
    display: "super AMOLED, HDR10",
    Platform: "Android 7.0 (Nougat)",
    memory: "64GB ROM, 4GB RAM",
    camera: "12 MP",
    selfie: "8 MP",
  },
  {
    id: 2,
    image: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s9-1.jpg",
    name: "samsung galaxy s9",
    launch: "2018, march 25",
    body: "147.9x68.7 mm",
    display: "super AMOLED, HDR10",
    Platform: "Android 8.0 (Oreo)",
    memory: "64GB ROM, 4GB RAM",
    camera: "12 MP",
    selfie: "8 MP",
  },
  {
    id: 3,
    image: "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s10-1.jpg",
    name: "samsung galaxy s10",
    launch: "2019, february 20",
    body: "149.9x70.4 mm",
    display: "Dynamic AMOLED, HDR10+",
    Platform: "Android 9.0 (Pie)",
    memory: "64GB ROM, 4GB RAM",
    camera: "12 MP",
    selfie: "8 MP",
  },
  {
    id: 4,
    image:
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s20-5g-r1.jpg",
    name: "samsung galaxy s20",
    launch: "2020, february 11",
    body: "151.7x69.1 mm",
    display: "Dynamic AMOLED 2x, HDR10+",
    Platform: "Android 10",
    memory: "128GB ROM, 8GB RAM",
    camera: "12pm, 64mp, 12mp",
    selfie: "10 MP",
  },
  {
    id: 5,
    image:
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-5g-0.jpg",
    name: "samsung galaxy s21 5G",
    launch: "2021, january 14",
    body: "151.7x72.2 mm",
    display: "Dynamic AMOLED, HDR10+",
    Platform: "Android 11 One UI 6.1",
    memory: "128GB ROM, 8GB RAM",
    camera: "12MP, 64mp, 12pm",
    selfie: "12 MP",
  },
  {
    id: 6,
    image:
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s21-ultra-5g-1.jpg",
    name: "samsung galaxy s22 ULTRA",
    launch: "2022, fabruary 09",
    body: "163.3x77.9 mm",
    display: "Dynamic AMOLED, HDR10+",
    Platform: "Android 12 ",
    memory: "128GB ROM, 8GB RAM",
    camera: "108MP",
    selfie: "40MP",
  },
  {
    id: 7,
    image:
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-s23-ultra-5g-1.jpg",
    name: "samsung galaxy s23 ULTRA",
    launch: "2023, february 01",
    body: "163.4x78.1 mm",
    display: "Dynamic AMOLED, HDR10+",
    Platform: "Android 13 onw UI 6.1",
    memory: "512GB ROM, 12GB RAM",
    camera: "200MP, 10mp, 10mp",
    selfie: "12 MP",
  },
  {
    id: 8,
    image:
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-note9-1.jpg",
    name: "samsung galaxy Note 9",
    launch: "2018, August 09",
    body: "161.9x76.1 mm",
    display: "super AMOLED, HDR10",
    Platform: "Android 8.1 (0reo), ONE UI 2.5",
    memory: "128GB ROM, 6GB RAM",
    camera: "12MP, 12pm,",
    selfie: "8 MP",
  },
  {
    id: 9,
    image:
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-note10-plus-aura-glow.jpg",
    name: "samsung galaxy Note 10+",
    launch: "2019, August 07",
    body: "162.9x77.1 mm",
    display: "Dynamic AMOLED, HDR10+",
    Platform: "Android 9.0 (pie), One UI 4",
    memory: "256GB ROM, 12GB RAM",
    camera: "12MP, 12mp, 16mp",
    selfie: "10MP",
  },
  {
    id: 10,
    image:
      "https://fdn2.gsmarena.com/vv/pics/samsung/samsung-galaxy-note20-ultra-1.jpg",
    name: "samsung galaxy note 20 ULTRA",
    launch: "2017, march 29",
    body: "164.9x77.2 mm",
    display: "Dynamic AMOLED 2x, HDR10+",
    Platform: "Android 10, One Ui 5",
    memory: "128GB ROM, 12GB RAM",
    camera: "108 MP,12mp, 12mp",
    selfie: "10MP",
  },
  {
    id: 11,
    image: "https://www.gsmarena.com/apple_iphone_6-pictures-6378.php",
    name: "iphone 6",
    launch: "2014, september 09",
    body: "138.9x6.9 mm",
    display: "IPS LCD",
    Platform: "iOS 8",
    memory: "16GB ROM, 1GB ROM",
    camera: "8mp",
    selfie: "1.2MP",
  },
  {
    id: 12,
    image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-7-1.jpg",
    name: "iphone 7",
    launch: "2016, september 07",
    body: "138.3x67.2 mm",
    display: "Retina IPS LCD",
    Platform: "IOS 10.0.1",
    memory: "32GB ROM, 2GB RAM",
    camera: "12MP",
    selfie: "7MP",
  },
  {
    id: 13,
    image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-8-new-1.jpg",
    name: "iphone 8",
    launch: "2017,september 12",
    body: "138.9x67.2 mm",
    display: "Retina IPS LCD, 625 nits",
    Platform: "iOS 11,",
    memory: "64GB ROM, 2GB RAM",
    camera: "12mp",
    selfie: "7MP",
  },
  {
    id: 14,
    image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-se-2020-2.jpg",
    name: "iphone SE",
    launch: "2020, April 15",
    body: "138.4x67.2 mm",
    display: "Retina IPS LCD",
    Platform: "IOS 13",
    memory: "64GB ROM, 3GB RAM",
    camera: "12mp",
    selfie: "7MP",
  },
  {
    id: 15,
    image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-x-new-1.jpg",
    name: "iphone x",
    launch: "2017, september 12",
    body: "143.9x70.2 mm",
    display: "Super Retina OLED, HDR10, Dolby Vision",
    Platform: "IOS 11.1.1",
    memory: "64GB ROM, 3GB RAM",
    camera: " 12mp, 12mp",
    selfie: "7MP",
  },
  {
    id: 16,
    image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-11-1.jpg",
    name: "iphone 11",
    launch: "2019, september 10",
    body: "150.9x75.2 mm",
    display: "Liquid Retina IPS LCD",
    Platform: "IOS 13,",
    memory: "64GB ROM, 4GB RAM",
    camera: "12mp, 12mp",
    selfie: "12MP",
  },
  {
    id: 17,
    image: "",
    name: "iphone 12",
    launch: "2020, October 13",
    body: "146.9x71.2 mm",
    display: "Super Retrina XDR OLED, HDR10, Dolby Vision",
    Platform: "IOS 14.1",
    memory: "64GB ROM, 4GB RAM",
    camera: "12mp, 12mp",
    selfie: "12MP",
  },
  {
    id: 18,
    image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-12-r1.jpg",
    name: "samsung galaxy note 20 ULTRA",
    launch: "2017, march 29",
    body: "164.9x77.2 mm",
    display: "Dynamic AMOLED 2x, HDR10+",
    Platform: "Android 10, One Ui 5",
    memory: "128GB ROM, 12GB RAM",
    camera: "108 MP,12mp, 12mp",
    selfie: "10MP",
  },
  {
    id: 19,
    image: "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-13-01.jpg",
    name: "iphone 13",
    launch: "2021, september 24",
    body: "146.9x71.2 mm",
    display: "Super Retina, XDR, OLED, HDR10",
    Platform: "IOS 15",
    memory: "128GB ROM, 4GB RAM",
    camera: "12mp, 12mp",
    selfie: "12MP",
  },
  {
    id: 20,
    image:
      "https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg",
    name: "iphone 14",
    launch: "2022 september 07",
    body: "160.9x77.6 mm",
    display: "LTPO Super Retina XDR OLED",
    Platform: "IOS 16",
    memory: "128GB ROM, 6GB RAM",
    camera: "48 MP,12mp, 12mp",
    selfie: "12MP",
  },
];

export default phone;
